### ISSUE TITLE
config_path parameter of CommonFactory does not work

### ISSUE THREAD

**Issue by ConnectDIY** [th2-net/th2-common-py#7]
config_path parameter of CommonFactory does not work because default values in \__init__ declaration are calculated before the following code in common_factory.py

```
        if config_path is not None:
            CommonFactory.CONFIG_DEFAULT_PATH = config_path
```

factory = CommonFactory(config_path=...)
![изображение](https://user-images.githubusercontent.com/25672975/99960290-8c2ff280-2d9d-11eb-93ca-e85f43738970.png)

**Comment by RaevskiySV** [comment]
Thanks for the provided issue.
This behavior is fixed in version 2.2.4
